const ipsumText = [
  // Wikipedia glossary of video game terms scrape
  "1up",
  "3d graphics",
  "32-bit",
  "aaa",
  "action point",
  "adventure game",
  "aiming down sights",
  "animatic",
  "area of effect",
  "assault mode",
  "attract mode",
  "auto battler",
  "battle pass",
  "bonus stage",
  "bottomless pit",
  "bullshot",
  "capture the flag",
  "character class",
  "chiptune",
  "closed beta",
  "compulsion loop",
  "construction and management simulation",
  "controller",
  "corruptor",
  "credit-feeding",
  "cut-in",
  "damage per second",
  "dead zone",
  "developer",
  "digital rights management",
  "dpm",
  "drop-out",
  "dynamic game difficulty balancing",
  "emulator",
  "esp cheats",
  "farming",
  "first-party developer",
  "flip-screen",
  "fps",
  "free look",
  "game engine",
  "game port",
  "gank",
  "gib",
  "gold sink",
  "grinding",
  "head bob",
  "heat map",
  "horde mode",
  "influencer marketing",
  "invisible wall",
  "jrpg",
  "kill screen",
  "knock-back",
  "last hitting",
  "level",
  "light gun",
  "loot system",
  "main quest",
  "matchmaking",
  "metroidvania",
  "minigame",
  "mode",
  "mudflation",
  "multiplayer online battle arena",
  "nerf",
  "non-player character",
  "on-disc dlc",
  "open world",
  "paddle",
  "pause",
  "pervasive game",
  "pixel hunting",
  "player versus environment",
  "point of no return",
  "power spike",
  "publisher",
  "quicksave",
  "random encounter",
  "remorting",
  "retrogaming",
  "rng",
  "role-playing video game",
  "rubber banding",
  "save point",
  "screen cheat",
  "secret character",
  "shovelware",
  "single-player",
  "skirmish mode",
  "spawn",
  "split-screen multiplayer",
  "strategy guide",
  "survival game",
  "technology tree",
  "theorycraft",
  "time attack",
  "touchscreen",
  "triple jump",
  "underpowered",
  "vaporware",
  "waggle",
  "wall climb",
  "wanted level",
  "whale",
  "wrapping",
  "zero-player game",
  // Scraped Best Game List 
  "God of War",
  "Call of Duty: Modern Warfare 2",
  "Metal Gear Solid V: The Phantom Pain",
  "Portal 2",
  "The Last of Us",
  "The Legend of Zelda: Majora's Mask",
  "The Legend of Zelda: A Link to the Past",
  "Halo 2",
  "Red Dead Redemption",
  "The Legend of Zelda: Collector's Edition",
  "LittleBigPlanet",
  "Grand Theft Auto: Vice City",
  "Grand Theft Auto: San Andreas",
  "Baldur's Gate",
  "Gran Turismo",
  "The Legend of Zelda: The Wind Waker",
  "The Elder Scrolls V: Skyrim",
  "The Legend of Zelda: Twilight Princess",
  "Mass Effect 2",
  "Batman: Arkham City",
  "The Orange Box",
  "Resident Evil 4",
  "GoldenEye 007",
  "NFL 2K1",
  "Halo: Combat Evolved",
  "Super Mario Odyssey",
  "Grand Theft Auto III",
  "Metroid Prime",
  "Perfect Dark",
  "The Legend of Zelda: Breath of the Wild",
  "Grand Theft Auto V",
  "Red Dead Redemption 2",
  "Super Mario Galaxy",
  "SoulCalibur",
  "Grand Theft Auto IV",
  "The Legend of Zelda: Ocarina of Time",
  // Random website
  "1-Up",
  "A",
  "AA",
  "AAA",
  "Achievements",
  "AFK",
  "Aggro",
  "AI",
  "Aimbot",
  "Alpha",
  "Animation Cancel",
  "Ambient Occlusion",
  "Anti-Aliasing",
  "AoE",
  "Assist",
  "Avatar",
  "Ban",
  "Barrel Stuffing",
  "Beat 'Em Up",
  "Beta",
  "Bonus",
  "Boosting",
  "Boss",
  "Camping/Active Camping",
  "Campaign",
  "Casual",
  "Chams",
  "Character design",
  "Cheat",
  "Checkpoint",
  "Chems",
  "Class",
  "Combo",
  "Commonwealth",
  "Continue",
  "Console",
  "Controller",
  "Co-op",
  "CoD",
  "CP",
  "Creeps/CS",
  "Crowd control",
  "Critical Hit",
  "Cutscene",
  "Deathmatch",
  "Debuff",
  "Demo",
  "Die-and-Retry",
  "Difficulty",
  "DLC",
  "D-Pad",
  "DPS",
  "Draw distance",
  "Driving simulator",
  "DRM",
  "Dual Wield",
  "Easter egg",
  "Emulator",
  "Epistle ",
  "Exploit",
  "Faceroll",
  "Fatality",
  "Farming",
  "Feeding",
  "FOV",
  "Fighting Game",
  "Flying Simulator",
  "FPS",
  "Frag",
  "Frame",
  "FP",
  "GameBattles",
  "Game Over",
  "Gamer",
  "Ghosting",
  "God Mode",
  "GG",
  "GG no re",
  "GG ez",
  "Gimp",
  "Glitch",
  "Griefing",
  "Grinding",
  "Guard",
  "Hacker",
  "Healer",
  "Headshot",
  "Hit Points (HP)",
  "Holy Trinity",
  "Indie",
  "Job",
  "JRPG",
  "Juan",
  "KDR",
  "Kick",
  "Kite",
  "Kill stealing",
  "KK",
  "KO",
  "Konami code",
  "LAN",
  "LoL",
  "Level (experience)",
  "Level (map)",
  "Level design",
  "Mana",
  "Manic shooter",
  "Map",
  "Magic Points (MP)",
  "MLG",
  "MMO",
  "MOBA",
  "Model",
  "Mute",
  "Nerf",
  "Noob",
  "Noob tube",
  "NPC",
  "OHKO",
  "One-shot-kill",
  "OP",
  "Open world",
  "OST",
  "Party game",
  "Permadeath",
  "Platformer",
  "Point-and-click",
  "Pre-firing",
  "PvP",
  "PvE",
  "Quickscope",
  "QQ",
  "QTE",
  "Ragequit",
  "Respawn",
  "Resolution",
  "Rekt",
  "RNG",
  "Rocket jump",
  "RPG",
  "RQ",
  "RTS",
  "Rush",
  "Sandbox",
  "Screen-peeking",
  "Shoot 'em up",
  "Sidescroller",
  "Sidequest",
  "Smoothskin",
  "Smurf",
  "SnD",
  "Speedhacks",
  "Speedrun",
  "Spoiler",
  "Sprite",
  "Stats",
  "Strafing",
  "Sweaty goal",
  "SWTOR",
  "Tank",
  "Trickshot",
  "Troll/Trolling",
  "Tryhard",
  "Twink",
  "ÜberCharge",
  "VAC",
  "Warrior",
  "Walling/Wall hack",
  "WoW",
  "Wombo Combo",
  "W+M1",
  "XP",
  "Z-targeting",
  // Consoles
  "Nintendo DS",
  "Game Boy",
  "Game Boy Color",
  "PlayStation",
  'PlayStation 2',
  "PlayStation3",
  "PlayStation 4",
  "Wii",
  "Wii U",
  "Xbox",
  "Xbox 360",
  "Xbox One",
  "GBA",
  "Game Boy Advance",
  "GameCube",
  "Nintendo Switch",
  "Nintendo 3DS",
  "PSP",
  "PlayStation Portable",
  "PlayStation Vita",
  "NES",
  "SNES",
  "Sega Genesis",
  "Nintendo 64",
  "Atari 2600",
  "Sega Saturn",
  "Dreamcast",
  // Modern Big 3
  "Nintendo",
  "Sony",
  "Microsoft",
  // Franchises
  "Mario",
  "Pokemon",
  "Super Mario",
  "Call of Duty",
  "Grand Theft Auto",
  "GTA",
  "Tetris",
  "The Sims",
  "Final Fantasy",
  "Need for Speed",
  "Mario Kart",
  "Sonic the Hedgehog",
  "Assassin's Creed",
  "Madden",
  "The Legend of Zelda",
  "Resident Evil",
  "NBA 2K",
  "Dragon Quest",
  "Gran Turismo",
  "Tomb Raider",
  "Halo",
  "Just Dance",
  "The Oregon Trail",
  "Monster Hunter",
  "WWE 2K",
  "Super Smash Bros.",
  "Donkey Kong",
  "Battlefield",
  "Metal Gear",
  "Dragon Ball",
  "Borderlands",
  "Mario Party",
  "Crash Bandicoot",
  "Bejeweled",
  "Counter-Strike",
  "Far Cry",
  "Mortal Kombat",
  "Tekken",
  "Uncharted",
  "Street Fighter",
  "Wii Fit",
  "Pac-Man",
  "Red Dead",
  "The Witcher",
  "Guitar Hero",
  "Civilization",
  "Medal of Honor",
  "Kirby",
  "NBA Live",
  "Mega Man",
  "Animal Crossing",
  "Brain Age",
  "God of War",
  "Star Wars: Battlefront",
  "Tom Clancy's Splinter Cell",
  "Kingdom Hearts",
  "Tony Hawk's",
  "Command & Conquer",
  "Half-Life",
  "Kinect",
  "Dark Souls",
  "Ratchet & Clank",
  "Gears of War",
  "Rayman",
  "BioShock",
  "Tom Clancy's Ghost Recon",
  "Age of Empires",
  "Total War",
  "Devil May Cry",
  "Castlevania",
  "Frogger",
  "Spyro",
  "Mass Effect",
  "SimCity",
]

module.exports = ipsumText;