const ipsumText = [
  // Wikipedia glossary of video game terms scrape
  "1up",
  "3d graphics",
  "32-bit",
  "aaa",
  "action point",
  "adventure game",
  "aiming down sights",
  "animatic",
  "aoe",
  "assault mode",
  "attract mode",
  "auto battler",
  "battle pass",
  "bonus stage",
  "bottomless pit",
  "bullshot",
  "capture the flag",
  "character class",
  "chiptune",
  "closed beta",
  "compulsion loop",
  "construction and management simulation",
  "controller",
  "corruptor",
  "credit-feeding",
  "cut-in",
  "damage per second",
  "dead zone",
  "developer",
  "digital rights management",
  "dpm",
  " drop-out",
  "dynamic game difficulty balancing",
  "emulator",
  "esp cheats",
  "farming",
  "first-party developer",
  "flip-screen",
  "fps",
  "free look",
  "game engine",
  "game port",
  "gank",
  "gib",
  "gold sink",
  "grinding",
  "head bob",
  "heat map",
  "horde mode",
  "influencer marketing",
  "invisible wall",
  "jrpg",
  "kill screen",
  "knock-back",
  "last hitting",
  "level",
  "light gun",
  "loot system",
  "main quest",
  "matchmaking",
  "metroidvania",
  "minigame",
  "mode",
  "mudflation",
  "multiplayer online battle arena",
  "nerf",
  "non-player character",
  "on-disc dlc",
  "open world",
  "paddle",
  "pause",
  "pervasive game",
  "pixel hunting",
  "player versus environment",
  "point of no return",
  "power spike",
  "publisher",
  "quicksave",
  "random encounter",
  "remorting",
  "retrogaming",
  "rng",
  "role-playing video game",
  "rubber banding",
  "save point",
  "screen cheat",
  "secret character",
  "shovelware",
  "single-player",
  "skirmish mode",
  "spawn",
  "split-screen multiplayer",
  "strategy guide",
  "survival game",
  "technology tree",
  "theorycraft",
  "time attack",
  "touchscreen",
  "triple jump",
  "underpowered",
  "vaporware",
  "waggle",
  "wall climb",
  "wanted level",
  "whale",
  "wrapping",
  "zero-player game",
  // Random website
  "1-Up",
  "A",
  "AA",
  "AAA",
  "Achievements",
  "AFK",
  "Aggro",
  "AI",
  "Aimbot",
  "Alpha",
  "Animation Cancel",
  "Ambient Occlusion",
  "Anti-Aliasing",
  "AoE",
  "Assist",
  "Avatar",
  "Ban",
  "Barrel Stuffing",
  "Beat 'Em Up",
  "Beta",
  "Bonus",
  "Boosting",
  "Boss",
  "Camping/Active Camping",
  "Campaign",
  "Casual",
  "Chams",
  "Character design",
  "Cheat",
  "Checkpoint",
  "Chems",
  "Class",
  "Combo",
  "Commonwealth",
  "Continue",
  "Console",
  "Controller",
  "Co-op",
  "CoD",
  "CP",
  "Creeps/CS",
  "Crowd control",
  "Critical Hit",
  "Cutscene",
  "Deathmatch",
  "Debuff",
  "Demo",
  "Die-and-Retry",
  "Difficulty",
  "DLC",
  "D-Pad",
  "DPS",
  "Draw distance",
  "Driving simulator",
  "DRM",
  "Dual Wield",
  "Easter egg",
  "Emulator",
  "Epistle ",
  "Exploit",
  "Faceroll",
  "Fatality",
  "Farming",
  "Feeding",
  "FOV",
  "Fighting Game",
  "Flying Simulator",
  "FPS",
  "Frag",
  "Frame",
  "FP",
  "GameBattles",
  "Game Over",
  "Gamer",
  "Ghosting",
  "God Mode",
  "GG",
  "GG no re",
  "GG ez",
  "Gimp",
  "Glitch",
  "Griefing",
  "Grinding",
  "Guard",
  "Hacker",
  "Healer",
  "Headshot",
  "Hit Points (HP)",
  "Holy Trinity",
  "Indie",
  "Job",
  "JRPG",
  "Juan",
  "KDR",
  "Kick",
  "Kite",
  "Kill stealing",
  "KK",
  "KO",
  "Konami code",
  "LAN",
  "LoL",
  "Level (experience)",
  "Level (map)",
  "Level design",
  "Mana",
  "Manic shooter",
  "Map",
  "Magic Points (MP)",
  "MLG",
  "MMO",
  "MOBA",
  "Model",
  "Mute",
  "Nerf",
  "Noob",
  "Noob tube",
  "NPC",
  "OHKO",
  "One-shot-kill",
  "OP",
  "Open world",
  "OST",
  "Party game",
  "Permadeath",
  "Platformer",
  "Point-and-click",
  "Pre-firing",
  "PvP",
  "PvE",
  "Quickscope",
  "QQ",
  "QTE",
  "Ragequit",
  "Respawn",
  "Resolution",
  "Rekt",
  "RNG",
  "Rocket jump",
  "RPG",
  "RQ",
  "RTS",
  "Rush",
  "Sandbox",
  "Screen-peeking",
  "Shoot 'em up",
  "Sidescroller",
  "Sidequest",
  "Smoothskin",
  "Smurf",
  "SnD",
  "Speedhacks",
  "Speedrun",
  "Spoiler",
  "Sprite",
  "Stats",
  "Strafing",
  "Sweaty goal",
  "SWTOR",
  "Tank",
  "Trickshot",
  "Troll/Trolling",
  "Tryhard",
  "Twink",
  "ÜberCharge",
  "VAC",
  "Warrior",
  "Walling/Wall hack",
  "WoW",
  "Wombo Combo",
  "W+M1",
  "XP",
  "Z-targeting",
]

module.exports = ipsumText;